---
# ====== Application: ManageCollege ==========================
identification: 
  name: ManageCollege
  alias: MANAGECOLLEGE
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 28120928708491307752

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_HY3

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: ManageCollege

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 28120929523324307753

navigation-bar: 
  implementation: List
  list: Navigation Bar # 28120930772073307756
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 15617959033251

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: ManageCollege

component-settings: 
- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 28120924273304307749
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15617319818222

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 28120924505070307750
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 15617319818223

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 28120924812699307750
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 15617319818229

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 28120925172202307750
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 15617319818229

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 28120925456876307750
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 15617319818232

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 28120925787626307750
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 15617319818232

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 28120926011543307751
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 15617319818232

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 28120926346152307751
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 15617319818232

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 28120926662512307751
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15617319818236

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 28120926965722307751
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15617319818239

- # ====== Component Setting: NATIVE_IR ========================
  id: 28120927287326307751
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15617319818240

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 28120927594367307751
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15617319818240

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 28120927873873307752
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15617319818245

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 28120928184176307752
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 15617319818245

