CREATE TABLE departments (
    dept_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name VARCHAR2(100) NOT NULL
);
CREATE TABLE students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    dept_id NUMBER,
    FOREIGN KEY (dept_id) REFERENCES departments(dept_id)
);
CREATE TABLE teachers (
    teacher_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    dept_id NUMBER,
    FOREIGN KEY (dept_id) REFERENCES departments(dept_id)
);
CREATE TABLE courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR2(100),
    dept_id NUMBER,
    FOREIGN KEY (dept_id) REFERENCES departments(dept_id)
);
CREATE TABLE attendance (
    attendance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER,
    course_id NUMBER,
    attendance_date DATE DEFAULT SYSDATE,
    status VARCHAR2(10),
    FOREIGN KEY (student_id) REFERENCES students(student_id),
    FOREIGN KEY (course_id) REFERENCES courses(course_id)
);
INSERT INTO departments (dept_name) VALUES ('Computer Science');
INSERT INTO departments (dept_name) VALUES ('Mechanical Engineering');
INSERT INTO departments (dept_name) VALUES ('Electrical Engineering');
INSERT INTO students (student_name, email, dept_id) VALUES ('John Doe', 'john.doe@example.com', 1);
INSERT INTO students (student_name, email, dept_id) VALUES ('Jane Smith', 'jane.smith@example.com', 2);
INSERT INTO teachers (teacher_name, email, dept_id) VALUES ('Dr. Alan Turing', 'alan.turing@example.com', 1);
INSERT INTO teachers (teacher_name, email, dept_id) VALUES ('Dr. Nikola Tesla', 'nikola.tesla@example.com', 2);
INSERT INTO courses (course_name, dept_id) VALUES ('Data Structures', 1);
INSERT INTO courses (course_name, dept_id) VALUES ('Thermodynamics', 2);
INSERT INTO attendance (student_id, course_id, status) VALUES (1, 1, 'Present');
INSERT INTO attendance (student_id, course_id, status) VALUES (2, 2, 'Absent');
